filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    - decode_json_fields:
        fields: ["message"]
        target: ""
        overwrite_keys: true

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_labels:
      labels:
        environment: homelab
        infrastructure: 83rr-poweredge

# Output to Logstash (which will forward to OpenSearch)
output.logstash:
  hosts: ["logstash:5044"]

# Enable logging for debugging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Filebeat monitoring
monitoring:
  enabled: true
  elasticsearch:
    hosts: ["opensearch:9200"]